on: push

name: Docker Workflow

jobs:
  build_publish:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Docker Build
        run: |
          docker build . -t katie/roleypoly:${{ github.sha }}

      - name: Docker Login
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
      - name: Docker Push
        if: github.ref == 'refs/heads/master'
        run: | 
          docker push katie/roleypoly:${{ github.sha }}
    