on: 
  push:
    branches:
      - master
      - cicd

name: Docker Workflow

jobs:
  build_publish:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Docker Login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  
      - name: Docker Build
        run: |
          docker build . -t katie/roleypoly:${{ github.sha }}
      
      - name: Docker Push
        run: | 
          docker push katie/roleypoly:${{ github.sha }}
    